// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: creator.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCreator = `-- name: CreateCreator :one
INSERT INTO creators (
    email,
    display_name,
    description,
    support_item,
    one_time_price_cents,
    one_time_character_limit,
    weekly_price_cents,
    weekly_allowance_chars
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, singleton, user_id, email, display_name, description, avatar_object_key, support_item, one_time_price_cents, one_time_character_limit, weekly_price_cents, weekly_allowance_chars, created_at, updated_at
`

type CreateCreatorParams struct {
	Email                 string `json:"email"`
	DisplayName           string `json:"display_name"`
	Description           string `json:"description"`
	SupportItem           string `json:"support_item"`
	OneTimePriceCents     int64  `json:"one_time_price_cents"`
	OneTimeCharacterLimit int32  `json:"one_time_character_limit"`
	WeeklyPriceCents      int64  `json:"weekly_price_cents"`
	WeeklyAllowanceChars  int32  `json:"weekly_allowance_chars"`
}

func (q *Queries) CreateCreator(ctx context.Context, arg CreateCreatorParams) (*Creator, error) {
	row := q.db.QueryRow(ctx, createCreator,
		arg.Email,
		arg.DisplayName,
		arg.Description,
		arg.SupportItem,
		arg.OneTimePriceCents,
		arg.OneTimeCharacterLimit,
		arg.WeeklyPriceCents,
		arg.WeeklyAllowanceChars,
	)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Description,
		&i.AvatarObjectKey,
		&i.SupportItem,
		&i.OneTimePriceCents,
		&i.OneTimeCharacterLimit,
		&i.WeeklyPriceCents,
		&i.WeeklyAllowanceChars,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCreator = `-- name: GetCreator :one
SELECT id, singleton, user_id, email, display_name, description, avatar_object_key, support_item, one_time_price_cents, one_time_character_limit, weekly_price_cents, weekly_allowance_chars, created_at, updated_at
FROM creators
WHERE singleton = TRUE
`

func (q *Queries) GetCreator(ctx context.Context) (*Creator, error) {
	row := q.db.QueryRow(ctx, getCreator)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Description,
		&i.AvatarObjectKey,
		&i.SupportItem,
		&i.OneTimePriceCents,
		&i.OneTimeCharacterLimit,
		&i.WeeklyPriceCents,
		&i.WeeklyAllowanceChars,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateCreatorSettings = `-- name: UpdateCreatorSettings :one
UPDATE creators
SET display_name = $1,
    description = $2,
    support_item = $3,
    one_time_price_cents = $4,
    one_time_character_limit = $5,
    weekly_price_cents = $6,
    updated_at = now()
WHERE singleton = TRUE
RETURNING id, singleton, user_id, email, display_name, description, avatar_object_key, support_item, one_time_price_cents, one_time_character_limit, weekly_price_cents, weekly_allowance_chars, created_at, updated_at
`

type UpdateCreatorSettingsParams struct {
	DisplayName           string `json:"display_name"`
	Description           string `json:"description"`
	SupportItem           string `json:"support_item"`
	OneTimePriceCents     int64  `json:"one_time_price_cents"`
	OneTimeCharacterLimit int32  `json:"one_time_character_limit"`
	WeeklyPriceCents      int64  `json:"weekly_price_cents"`
}

func (q *Queries) UpdateCreatorSettings(ctx context.Context, arg UpdateCreatorSettingsParams) (*Creator, error) {
	row := q.db.QueryRow(ctx, updateCreatorSettings,
		arg.DisplayName,
		arg.Description,
		arg.SupportItem,
		arg.OneTimePriceCents,
		arg.OneTimeCharacterLimit,
		arg.WeeklyPriceCents,
	)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Description,
		&i.AvatarObjectKey,
		&i.SupportItem,
		&i.OneTimePriceCents,
		&i.OneTimeCharacterLimit,
		&i.WeeklyPriceCents,
		&i.WeeklyAllowanceChars,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertCreatorUser = `-- name: UpsertCreatorUser :one
INSERT INTO creators (
    email,
    display_name,
    description,
    support_item,
    one_time_price_cents,
    one_time_character_limit,
    weekly_price_cents,
    weekly_allowance_chars,
    user_id
)
VALUES ($1, $2, '', $3, $4, $5, $6, 2000, $7)
ON CONFLICT (singleton) DO UPDATE
SET user_id = EXCLUDED.user_id,
    email = EXCLUDED.email,
    updated_at = now()
RETURNING id, singleton, user_id, email, display_name, description, avatar_object_key, support_item, one_time_price_cents, one_time_character_limit, weekly_price_cents, weekly_allowance_chars, created_at, updated_at
`

type UpsertCreatorUserParams struct {
	Email                 string      `json:"email"`
	DisplayName           string      `json:"display_name"`
	SupportItem           string      `json:"support_item"`
	OneTimePriceCents     int64       `json:"one_time_price_cents"`
	OneTimeCharacterLimit int32       `json:"one_time_character_limit"`
	WeeklyPriceCents      int64       `json:"weekly_price_cents"`
	UserID                pgtype.Int8 `json:"user_id"`
}

func (q *Queries) UpsertCreatorUser(ctx context.Context, arg UpsertCreatorUserParams) (*Creator, error) {
	row := q.db.QueryRow(ctx, upsertCreatorUser,
		arg.Email,
		arg.DisplayName,
		arg.SupportItem,
		arg.OneTimePriceCents,
		arg.OneTimeCharacterLimit,
		arg.WeeklyPriceCents,
		arg.UserID,
	)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Description,
		&i.AvatarObjectKey,
		&i.SupportItem,
		&i.OneTimePriceCents,
		&i.OneTimeCharacterLimit,
		&i.WeeklyPriceCents,
		&i.WeeklyAllowanceChars,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
