// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dome.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentDomePrompt = `-- name: GetCurrentDomePrompt :one
SELECT id, slug, body, created_by_user_id, created_at
FROM dome_prompts
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetCurrentDomePrompt(ctx context.Context) (*DomePrompt, error) {
	row := q.db.QueryRow(ctx, getCurrentDomePrompt)
	var i DomePrompt
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Body,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return &i, err
}

const getDomeNoteByID = `-- name: GetDomeNoteByID :one
SELECT id, prompt_id, author_user_id, parent_id, body, is_anonymous, emoji, shape, color, created_at
FROM dome_notes
WHERE id = $1
`

func (q *Queries) GetDomeNoteByID(ctx context.Context, id int64) (*DomeNote, error) {
	row := q.db.QueryRow(ctx, getDomeNoteByID, id)
	var i DomeNote
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.AuthorUserID,
		&i.ParentID,
		&i.Body,
		&i.IsAnonymous,
		&i.Emoji,
		&i.Shape,
		&i.Color,
		&i.CreatedAt,
	)
	return &i, err
}

const getDomePromptByID = `-- name: GetDomePromptByID :one
SELECT id, slug, body, created_by_user_id, created_at
FROM dome_prompts
WHERE id = $1
`

func (q *Queries) GetDomePromptByID(ctx context.Context, id int64) (*DomePrompt, error) {
	row := q.db.QueryRow(ctx, getDomePromptByID, id)
	var i DomePrompt
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Body,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return &i, err
}

const getDomePromptBySlug = `-- name: GetDomePromptBySlug :one
SELECT id, slug, body, created_by_user_id, created_at
FROM dome_prompts
WHERE slug = $1
`

func (q *Queries) GetDomePromptBySlug(ctx context.Context, slug string) (*DomePrompt, error) {
	row := q.db.QueryRow(ctx, getDomePromptBySlug, slug)
	var i DomePrompt
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Body,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return &i, err
}

const insertDomeNote = `-- name: InsertDomeNote :one
INSERT INTO dome_notes (prompt_id, author_user_id, parent_id, body, is_anonymous, emoji, shape, color)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, prompt_id, author_user_id, parent_id, body, is_anonymous, emoji, shape, color, created_at
`

type InsertDomeNoteParams struct {
	PromptID     int64       `json:"prompt_id"`
	AuthorUserID int64       `json:"author_user_id"`
	ParentID     pgtype.Int8 `json:"parent_id"`
	Body         string      `json:"body"`
	IsAnonymous  bool        `json:"is_anonymous"`
	Emoji        string      `json:"emoji"`
	Shape        string      `json:"shape"`
	Color        string      `json:"color"`
}

func (q *Queries) InsertDomeNote(ctx context.Context, arg InsertDomeNoteParams) (*DomeNote, error) {
	row := q.db.QueryRow(ctx, insertDomeNote,
		arg.PromptID,
		arg.AuthorUserID,
		arg.ParentID,
		arg.Body,
		arg.IsAnonymous,
		arg.Emoji,
		arg.Shape,
		arg.Color,
	)
	var i DomeNote
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.AuthorUserID,
		&i.ParentID,
		&i.Body,
		&i.IsAnonymous,
		&i.Emoji,
		&i.Shape,
		&i.Color,
		&i.CreatedAt,
	)
	return &i, err
}

const insertDomePrompt = `-- name: InsertDomePrompt :one
INSERT INTO dome_prompts (slug, body, created_by_user_id)
VALUES ($1, $2, $3)
RETURNING id, slug, body, created_by_user_id, created_at
`

type InsertDomePromptParams struct {
	Slug            string `json:"slug"`
	Body            string `json:"body"`
	CreatedByUserID int64  `json:"created_by_user_id"`
}

func (q *Queries) InsertDomePrompt(ctx context.Context, arg InsertDomePromptParams) (*DomePrompt, error) {
	row := q.db.QueryRow(ctx, insertDomePrompt, arg.Slug, arg.Body, arg.CreatedByUserID)
	var i DomePrompt
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Body,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return &i, err
}

const listDomeMembers = `-- name: ListDomeMembers :many
SELECT
    m.user_id,
    m.created_at,
    u.email,
    u.display_name
FROM dome_memberships m
JOIN users u ON u.id = m.user_id
ORDER BY m.created_at ASC, m.user_id ASC
`

type ListDomeMembersRow struct {
	UserID      int64              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
}

func (q *Queries) ListDomeMembers(ctx context.Context) ([]*ListDomeMembersRow, error) {
	rows, err := q.db.Query(ctx, listDomeMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDomeMembersRow
	for rows.Next() {
		var i ListDomeMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.CreatedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomeNotesByAuthor = `-- name: ListDomeNotesByAuthor :many
SELECT id, prompt_id, author_user_id, parent_id, body, is_anonymous, emoji, shape, color, created_at
FROM dome_notes
WHERE prompt_id = $1 AND author_user_id = $2
ORDER BY created_at ASC, id ASC
`

type ListDomeNotesByAuthorParams struct {
	PromptID     int64 `json:"prompt_id"`
	AuthorUserID int64 `json:"author_user_id"`
}

func (q *Queries) ListDomeNotesByAuthor(ctx context.Context, arg ListDomeNotesByAuthorParams) ([]*DomeNote, error) {
	rows, err := q.db.Query(ctx, listDomeNotesByAuthor, arg.PromptID, arg.AuthorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DomeNote
	for rows.Next() {
		var i DomeNote
		if err := rows.Scan(
			&i.ID,
			&i.PromptID,
			&i.AuthorUserID,
			&i.ParentID,
			&i.Body,
			&i.IsAnonymous,
			&i.Emoji,
			&i.Shape,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomeNotesByPrompt = `-- name: ListDomeNotesByPrompt :many
SELECT id, prompt_id, author_user_id, parent_id, body, is_anonymous, emoji, shape, color, created_at
FROM dome_notes
WHERE prompt_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListDomeNotesByPrompt(ctx context.Context, promptID int64) ([]*DomeNote, error) {
	rows, err := q.db.Query(ctx, listDomeNotesByPrompt, promptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DomeNote
	for rows.Next() {
		var i DomeNote
		if err := rows.Scan(
			&i.ID,
			&i.PromptID,
			&i.AuthorUserID,
			&i.ParentID,
			&i.Body,
			&i.IsAnonymous,
			&i.Emoji,
			&i.Shape,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomePrompts = `-- name: ListDomePrompts :many
SELECT
    p.id, p.slug, p.body, p.created_by_user_id, p.created_at,
    (
        SELECT count(*)::bigint
        FROM dome_notes n
        WHERE n.prompt_id = p.id
    ) AS note_count
FROM dome_prompts p
ORDER BY p.created_at DESC, p.id DESC
`

type ListDomePromptsRow struct {
	ID              int64              `json:"id"`
	Slug            string             `json:"slug"`
	Body            string             `json:"body"`
	CreatedByUserID int64              `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	NoteCount       int64              `json:"note_count"`
}

func (q *Queries) ListDomePrompts(ctx context.Context) ([]*ListDomePromptsRow, error) {
	rows, err := q.db.Query(ctx, listDomePrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDomePromptsRow
	for rows.Next() {
		var i ListDomePromptsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Body,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.NoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDomeMembership = `-- name: UpsertDomeMembership :exec
INSERT INTO dome_memberships (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) UpsertDomeMembership(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, upsertDomeMembership, userID)
	return err
}
