// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachMediaToMessage = `-- name: AttachMediaToMessage :execrows
UPDATE media_objects
SET message_id = $2
WHERE object_key = $1
  AND uploaded_by_user_id = $3
  AND purpose = 'attachment'
  AND message_id IS NULL
`

type AttachMediaToMessageParams struct {
	ObjectKey        string      `json:"object_key"`
	MessageID        pgtype.Int8 `json:"message_id"`
	UploadedByUserID int64       `json:"uploaded_by_user_id"`
}

func (q *Queries) AttachMediaToMessage(ctx context.Context, arg AttachMediaToMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachMediaToMessage, arg.ObjectKey, arg.MessageID, arg.UploadedByUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAttachmentsForMessage = `-- name: CountAttachmentsForMessage :one
SELECT count(*)::int AS n
FROM media_objects
WHERE message_id = $1
`

func (q *Queries) CountAttachmentsForMessage(ctx context.Context, messageID pgtype.Int8) (int32, error) {
	row := q.db.QueryRow(ctx, countAttachmentsForMessage, messageID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const deleteMediaObject = `-- name: DeleteMediaObject :exec
DELETE FROM media_objects
WHERE id = $1
  AND message_id IS NULL
`

func (q *Queries) DeleteMediaObject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMediaObject, id)
	return err
}

const getContentUnlock = `-- name: GetContentUnlock :one
SELECT id, message_id, guest_user_id, checkout_id, created_at
FROM content_unlocks
WHERE message_id = $1
  AND guest_user_id = $2
`

type GetContentUnlockParams struct {
	MessageID   int64 `json:"message_id"`
	GuestUserID int64 `json:"guest_user_id"`
}

func (q *Queries) GetContentUnlock(ctx context.Context, arg GetContentUnlockParams) (*ContentUnlock, error) {
	row := q.db.QueryRow(ctx, getContentUnlock, arg.MessageID, arg.GuestUserID)
	var i ContentUnlock
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.GuestUserID,
		&i.CheckoutID,
		&i.CreatedAt,
	)
	return &i, err
}

const getMediaObjectByID = `-- name: GetMediaObjectByID :one
SELECT id, object_key, purpose, kind, content_type, byte_size, original_filename, uploaded_by_user_id, message_id, created_at
FROM media_objects
WHERE id = $1
`

func (q *Queries) GetMediaObjectByID(ctx context.Context, id int64) (*MediaObject, error) {
	row := q.db.QueryRow(ctx, getMediaObjectByID, id)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Purpose,
		&i.Kind,
		&i.ContentType,
		&i.ByteSize,
		&i.OriginalFilename,
		&i.UploadedByUserID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return &i, err
}

const getMediaObjectByKey = `-- name: GetMediaObjectByKey :one
SELECT id, object_key, purpose, kind, content_type, byte_size, original_filename, uploaded_by_user_id, message_id, created_at
FROM media_objects
WHERE object_key = $1
`

func (q *Queries) GetMediaObjectByKey(ctx context.Context, objectKey string) (*MediaObject, error) {
	row := q.db.QueryRow(ctx, getMediaObjectByKey, objectKey)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Purpose,
		&i.Kind,
		&i.ContentType,
		&i.ByteSize,
		&i.OriginalFilename,
		&i.UploadedByUserID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return &i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, conversation_id, author_user_id, body, character_count, checkout_id, created_at, unlock_price_cents
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (*Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.AuthorUserID,
		&i.Body,
		&i.CharacterCount,
		&i.CheckoutID,
		&i.CreatedAt,
		&i.UnlockPriceCents,
	)
	return &i, err
}

const insertContentUnlock = `-- name: InsertContentUnlock :execrows
INSERT INTO content_unlocks (message_id, guest_user_id, checkout_id)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, guest_user_id) DO NOTHING
`

type InsertContentUnlockParams struct {
	MessageID   int64 `json:"message_id"`
	GuestUserID int64 `json:"guest_user_id"`
	CheckoutID  int64 `json:"checkout_id"`
}

func (q *Queries) InsertContentUnlock(ctx context.Context, arg InsertContentUnlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertContentUnlock, arg.MessageID, arg.GuestUserID, arg.CheckoutID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMediaObject = `-- name: InsertMediaObject :one
INSERT INTO media_objects (
    object_key,
    purpose,
    kind,
    content_type,
    byte_size,
    original_filename,
    uploaded_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, object_key, purpose, kind, content_type, byte_size, original_filename, uploaded_by_user_id, message_id, created_at
`

type InsertMediaObjectParams struct {
	ObjectKey        string `json:"object_key"`
	Purpose          string `json:"purpose"`
	Kind             string `json:"kind"`
	ContentType      string `json:"content_type"`
	ByteSize         int64  `json:"byte_size"`
	OriginalFilename string `json:"original_filename"`
	UploadedByUserID int64  `json:"uploaded_by_user_id"`
}

func (q *Queries) InsertMediaObject(ctx context.Context, arg InsertMediaObjectParams) (*MediaObject, error) {
	row := q.db.QueryRow(ctx, insertMediaObject,
		arg.ObjectKey,
		arg.Purpose,
		arg.Kind,
		arg.ContentType,
		arg.ByteSize,
		arg.OriginalFilename,
		arg.UploadedByUserID,
	)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Purpose,
		&i.Kind,
		&i.ContentType,
		&i.ByteSize,
		&i.OriginalFilename,
		&i.UploadedByUserID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return &i, err
}

const listMediaByMessageIDs = `-- name: ListMediaByMessageIDs :many
SELECT id, object_key, purpose, kind, content_type, byte_size, original_filename, uploaded_by_user_id, message_id, created_at
FROM media_objects
WHERE message_id = ANY($1::bigint[])
ORDER BY id ASC
`

func (q *Queries) ListMediaByMessageIDs(ctx context.Context, dollar_1 []int64) ([]*MediaObject, error) {
	rows, err := q.db.Query(ctx, listMediaByMessageIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*MediaObject
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.ID,
			&i.ObjectKey,
			&i.Purpose,
			&i.Kind,
			&i.ContentType,
			&i.ByteSize,
			&i.OriginalFilename,
			&i.UploadedByUserID,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnattachedAttachmentKeys = `-- name: ListUnattachedAttachmentKeys :many
SELECT id, object_key, purpose, kind, content_type, byte_size, original_filename, uploaded_by_user_id, message_id, created_at
FROM media_objects
WHERE uploaded_by_user_id = $1
  AND purpose = 'attachment'
  AND message_id IS NULL
  AND created_at < $2
ORDER BY id ASC
`

type ListUnattachedAttachmentKeysParams struct {
	UploadedByUserID int64              `json:"uploaded_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUnattachedAttachmentKeys(ctx context.Context, arg ListUnattachedAttachmentKeysParams) ([]*MediaObject, error) {
	rows, err := q.db.Query(ctx, listUnattachedAttachmentKeys, arg.UploadedByUserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*MediaObject
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.ID,
			&i.ObjectKey,
			&i.Purpose,
			&i.Kind,
			&i.ContentType,
			&i.ByteSize,
			&i.OriginalFilename,
			&i.UploadedByUserID,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlocksForGuest = `-- name: ListUnlocksForGuest :many
SELECT message_id
FROM content_unlocks
WHERE guest_user_id = $1
`

func (q *Queries) ListUnlocksForGuest(ctx context.Context, guestUserID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUnlocksForGuest, guestUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var message_id int64
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCreatorAvatarKey = `-- name: SetCreatorAvatarKey :one
UPDATE creators
SET avatar_object_key = $1,
    updated_at = now()
WHERE singleton = TRUE
RETURNING id, singleton, user_id, email, display_name, description, avatar_object_key, support_item, one_time_price_cents, one_time_character_limit, weekly_price_cents, weekly_allowance_chars, created_at, updated_at
`

func (q *Queries) SetCreatorAvatarKey(ctx context.Context, avatarObjectKey pgtype.Text) (*Creator, error) {
	row := q.db.QueryRow(ctx, setCreatorAvatarKey, avatarObjectKey)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Description,
		&i.AvatarObjectKey,
		&i.SupportItem,
		&i.OneTimePriceCents,
		&i.OneTimeCharacterLimit,
		&i.WeeklyPriceCents,
		&i.WeeklyAllowanceChars,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
