// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatRecoveryToken struct {
	ID             int64              `json:"id"`
	ConversationID int64              `json:"conversation_id"`
	GuestUserID    int64              `json:"guest_user_id"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Checkout struct {
	ID                      int64              `json:"id"`
	PublicID                pgtype.UUID        `json:"public_id"`
	Kind                    string             `json:"kind"`
	Status                  string             `json:"status"`
	GuestEmail              string             `json:"guest_email"`
	GuestUserID             pgtype.Int8        `json:"guest_user_id"`
	InitialMessage          pgtype.Text        `json:"initial_message"`
	AmountCents             int64              `json:"amount_cents"`
	Currency                string             `json:"currency"`
	CharacterLimit          pgtype.Int4        `json:"character_limit"`
	StripeCheckoutSessionID pgtype.Text        `json:"stripe_checkout_session_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CompletedAt             pgtype.Timestamptz `json:"completed_at"`
	TargetMessageID         pgtype.Int8        `json:"target_message_id"`
}

type ContentUnlock struct {
	ID          int64              `json:"id"`
	MessageID   int64              `json:"message_id"`
	GuestUserID int64              `json:"guest_user_id"`
	CheckoutID  int64              `json:"checkout_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID             int64              `json:"id"`
	GuestUserID    int64              `json:"guest_user_id"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	BlockedAt      pgtype.Timestamptz `json:"blocked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Creator struct {
	ID                    int64              `json:"id"`
	Singleton             bool               `json:"singleton"`
	UserID                pgtype.Int8        `json:"user_id"`
	Email                 string             `json:"email"`
	DisplayName           string             `json:"display_name"`
	Description           string             `json:"description"`
	AvatarObjectKey       pgtype.Text        `json:"avatar_object_key"`
	SupportItem           string             `json:"support_item"`
	OneTimePriceCents     int64              `json:"one_time_price_cents"`
	OneTimeCharacterLimit int32              `json:"one_time_character_limit"`
	WeeklyPriceCents      int64              `json:"weekly_price_cents"`
	WeeklyAllowanceChars  int32              `json:"weekly_allowance_chars"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Price500Cents         int64              `json:"price_500_cents"`
	Price1000Cents        int64              `json:"price_1000_cents"`
}

type DomeMembership struct {
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DomeNote struct {
	ID           int64              `json:"id"`
	PromptID     int64              `json:"prompt_id"`
	AuthorUserID int64              `json:"author_user_id"`
	ParentID     pgtype.Int8        `json:"parent_id"`
	Body         string             `json:"body"`
	IsAnonymous  bool               `json:"is_anonymous"`
	Emoji        string             `json:"emoji"`
	Shape        string             `json:"shape"`
	Color        string             `json:"color"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DomePrompt struct {
	ID              int64              `json:"id"`
	Slug            string             `json:"slug"`
	Body            string             `json:"body"`
	CreatedByUserID int64              `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type MediaObject struct {
	ID               int64              `json:"id"`
	ObjectKey        string             `json:"object_key"`
	Purpose          string             `json:"purpose"`
	Kind             string             `json:"kind"`
	ContentType      string             `json:"content_type"`
	ByteSize         int64              `json:"byte_size"`
	OriginalFilename string             `json:"original_filename"`
	UploadedByUserID int64              `json:"uploaded_by_user_id"`
	MessageID        pgtype.Int8        `json:"message_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID               int64              `json:"id"`
	ConversationID   int64              `json:"conversation_id"`
	AuthorUserID     int64              `json:"author_user_id"`
	Body             string             `json:"body"`
	CharacterCount   int32              `json:"character_count"`
	CheckoutID       pgtype.Int8        `json:"checkout_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UnlockPriceCents pgtype.Int8        `json:"unlock_price_cents"`
}

type Payment struct {
	ID                    int64              `json:"id"`
	CheckoutID            int64              `json:"checkout_id"`
	StripePaymentIntentID pgtype.Text        `json:"stripe_payment_intent_id"`
	AmountCents           int64              `json:"amount_cents"`
	Currency              string             `json:"currency"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StripeEvent struct {
	ID            int64              `json:"id"`
	StripeEventID string             `json:"stripe_event_id"`
	EventType     string             `json:"event_type"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
}

type Subscription struct {
	ID                   int64              `json:"id"`
	GuestUserID          int64              `json:"guest_user_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CharsUsed            int32              `json:"chars_used"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          int64              `json:"id"`
	FirebaseUid pgtype.Text        `json:"firebase_uid"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
