// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: penpal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeCheckout = `-- name: CompleteCheckout :execrows
UPDATE checkouts
SET status = 'completed',
    guest_user_id = $2,
    completed_at = now()
WHERE id = $1
  AND status = 'pending'
`

type CompleteCheckoutParams struct {
	ID          int64       `json:"id"`
	GuestUserID pgtype.Int8 `json:"guest_user_id"`
}

func (q *Queries) CompleteCheckout(ctx context.Context, arg CompleteCheckoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCheckout, arg.ID, arg.GuestUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCheckout = `-- name: CreateCheckout :one
INSERT INTO checkouts (
    kind,
    guest_email,
    initial_message,
    amount_cents,
    currency,
    character_limit,
    target_message_id,
    guest_user_id
)
VALUES ($1, $2, $3, $4, 'usd', $5, $6, $7)
RETURNING id, public_id, kind, status, guest_email, guest_user_id, initial_message, amount_cents, currency, character_limit, stripe_checkout_session_id, created_at, completed_at, target_message_id
`

type CreateCheckoutParams struct {
	Kind            string      `json:"kind"`
	GuestEmail      string      `json:"guest_email"`
	InitialMessage  pgtype.Text `json:"initial_message"`
	AmountCents     int64       `json:"amount_cents"`
	CharacterLimit  pgtype.Int4 `json:"character_limit"`
	TargetMessageID pgtype.Int8 `json:"target_message_id"`
	GuestUserID     pgtype.Int8 `json:"guest_user_id"`
}

func (q *Queries) CreateCheckout(ctx context.Context, arg CreateCheckoutParams) (*Checkout, error) {
	row := q.db.QueryRow(ctx, createCheckout,
		arg.Kind,
		arg.GuestEmail,
		arg.InitialMessage,
		arg.AmountCents,
		arg.CharacterLimit,
		arg.TargetMessageID,
		arg.GuestUserID,
	)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Kind,
		&i.Status,
		&i.GuestEmail,
		&i.GuestUserID,
		&i.InitialMessage,
		&i.AmountCents,
		&i.Currency,
		&i.CharacterLimit,
		&i.StripeCheckoutSessionID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.TargetMessageID,
	)
	return &i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (guest_user_id)
VALUES ($1)
RETURNING id, guest_user_id, last_activity_at, blocked_at, created_at
`

func (q *Queries) CreateConversation(ctx context.Context, guestUserID int64) (*Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, guestUserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.GuestUserID,
		&i.LastActivityAt,
		&i.BlockedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, author_user_id, body, character_count, checkout_id, unlock_price_cents)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, conversation_id, author_user_id, body, character_count, checkout_id, created_at, unlock_price_cents
`

type CreateMessageParams struct {
	ConversationID   int64       `json:"conversation_id"`
	AuthorUserID     int64       `json:"author_user_id"`
	Body             string      `json:"body"`
	CharacterCount   int32       `json:"character_count"`
	CheckoutID       pgtype.Int8 `json:"checkout_id"`
	UnlockPriceCents pgtype.Int8 `json:"unlock_price_cents"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (*Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.AuthorUserID,
		arg.Body,
		arg.CharacterCount,
		arg.CheckoutID,
		arg.UnlockPriceCents,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.AuthorUserID,
		&i.Body,
		&i.CharacterCount,
		&i.CheckoutID,
		&i.CreatedAt,
		&i.UnlockPriceCents,
	)
	return &i, err
}

const getCheckoutByPublicID = `-- name: GetCheckoutByPublicID :one
SELECT id, public_id, kind, status, guest_email, guest_user_id, initial_message, amount_cents, currency, character_limit, stripe_checkout_session_id, created_at, completed_at, target_message_id
FROM checkouts
WHERE public_id = $1
`

func (q *Queries) GetCheckoutByPublicID(ctx context.Context, publicID pgtype.UUID) (*Checkout, error) {
	row := q.db.QueryRow(ctx, getCheckoutByPublicID, publicID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Kind,
		&i.Status,
		&i.GuestEmail,
		&i.GuestUserID,
		&i.InitialMessage,
		&i.AmountCents,
		&i.Currency,
		&i.CharacterLimit,
		&i.StripeCheckoutSessionID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.TargetMessageID,
	)
	return &i, err
}

const getCheckoutByStripeSessionID = `-- name: GetCheckoutByStripeSessionID :one
SELECT id, public_id, kind, status, guest_email, guest_user_id, initial_message, amount_cents, currency, character_limit, stripe_checkout_session_id, created_at, completed_at, target_message_id
FROM checkouts
WHERE stripe_checkout_session_id = $1
`

func (q *Queries) GetCheckoutByStripeSessionID(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (*Checkout, error) {
	row := q.db.QueryRow(ctx, getCheckoutByStripeSessionID, stripeCheckoutSessionID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Kind,
		&i.Status,
		&i.GuestEmail,
		&i.GuestUserID,
		&i.InitialMessage,
		&i.AmountCents,
		&i.Currency,
		&i.CharacterLimit,
		&i.StripeCheckoutSessionID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.TargetMessageID,
	)
	return &i, err
}

const getConversationByGuestUserID = `-- name: GetConversationByGuestUserID :one
SELECT id, guest_user_id, last_activity_at, blocked_at, created_at
FROM conversations
WHERE guest_user_id = $1
`

func (q *Queries) GetConversationByGuestUserID(ctx context.Context, guestUserID int64) (*Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByGuestUserID, guestUserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.GuestUserID,
		&i.LastActivityAt,
		&i.BlockedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, guest_user_id, last_activity_at, blocked_at, created_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id int64) (*Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.GuestUserID,
		&i.LastActivityAt,
		&i.BlockedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getMessageByCheckoutID = `-- name: GetMessageByCheckoutID :one
SELECT id, conversation_id, author_user_id, body, character_count, checkout_id, created_at, unlock_price_cents
FROM messages
WHERE checkout_id = $1
`

func (q *Queries) GetMessageByCheckoutID(ctx context.Context, checkoutID pgtype.Int8) (*Message, error) {
	row := q.db.QueryRow(ctx, getMessageByCheckoutID, checkoutID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.AuthorUserID,
		&i.Body,
		&i.CharacterCount,
		&i.CheckoutID,
		&i.CreatedAt,
		&i.UnlockPriceCents,
	)
	return &i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (checkout_id, stripe_payment_intent_id, amount_cents, currency)
VALUES ($1, $2, $3, 'usd')
RETURNING id, checkout_id, stripe_payment_intent_id, amount_cents, currency, created_at
`

type InsertPaymentParams struct {
	CheckoutID            int64       `json:"checkout_id"`
	StripePaymentIntentID pgtype.Text `json:"stripe_payment_intent_id"`
	AmountCents           int64       `json:"amount_cents"`
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (*Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment, arg.CheckoutID, arg.StripePaymentIntentID, arg.AmountCents)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
	)
	return &i, err
}

const listConversations = `-- name: ListConversations :many
SELECT
    c.id,
    c.guest_user_id,
    c.last_activity_at,
    c.blocked_at,
    c.created_at,
    u.email AS guest_email,
    u.display_name AS guest_display_name,
    COALESCE((
        SELECT SUM(p.amount_cents)
        FROM payments p
        JOIN checkouts ch ON ch.id = p.checkout_id
        WHERE ch.guest_user_id = c.guest_user_id
          AND ch.status = 'completed'
    ), 0)::bigint AS total_paid_cents,
    EXISTS (
        SELECT 1
        FROM subscriptions s
        WHERE s.guest_user_id = c.guest_user_id
          AND s.status IN ('active', 'trialing', 'past_due')
          AND s.current_period_end > now()
    ) AS is_subscriber
FROM conversations c
JOIN users u ON u.id = c.guest_user_id
ORDER BY c.last_activity_at DESC
`

type ListConversationsRow struct {
	ID               int64              `json:"id"`
	GuestUserID      int64              `json:"guest_user_id"`
	LastActivityAt   pgtype.Timestamptz `json:"last_activity_at"`
	BlockedAt        pgtype.Timestamptz `json:"blocked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	GuestEmail       string             `json:"guest_email"`
	GuestDisplayName string             `json:"guest_display_name"`
	TotalPaidCents   int64              `json:"total_paid_cents"`
	IsSubscriber     bool               `json:"is_subscriber"`
}

func (q *Queries) ListConversations(ctx context.Context) ([]*ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuestUserID,
			&i.LastActivityAt,
			&i.BlockedAt,
			&i.CreatedAt,
			&i.GuestEmail,
			&i.GuestDisplayName,
			&i.TotalPaidCents,
			&i.IsSubscriber,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, author_user_id, body, character_count, checkout_id, created_at, unlock_price_cents
FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID int64) ([]*Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.AuthorUserID,
			&i.Body,
			&i.CharacterCount,
			&i.CheckoutID,
			&i.CreatedAt,
			&i.UnlockPriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCheckoutStatus = `-- name: SetCheckoutStatus :execrows
UPDATE checkouts
SET status = $2
WHERE id = $1
  AND status = 'pending'
`

type SetCheckoutStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetCheckoutStatus(ctx context.Context, arg SetCheckoutStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCheckoutStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCheckoutStripeSession = `-- name: SetCheckoutStripeSession :exec
UPDATE checkouts
SET stripe_checkout_session_id = $2
WHERE id = $1
`

type SetCheckoutStripeSessionParams struct {
	ID                      int64       `json:"id"`
	StripeCheckoutSessionID pgtype.Text `json:"stripe_checkout_session_id"`
}

func (q *Queries) SetCheckoutStripeSession(ctx context.Context, arg SetCheckoutStripeSessionParams) error {
	_, err := q.db.Exec(ctx, setCheckoutStripeSession, arg.ID, arg.StripeCheckoutSessionID)
	return err
}

const setConversationBlocked = `-- name: SetConversationBlocked :execrows
UPDATE conversations
SET blocked_at = now()
WHERE id = $1
  AND blocked_at IS NULL
`

func (q *Queries) SetConversationBlocked(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, setConversationBlocked, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setConversationUnblocked = `-- name: SetConversationUnblocked :execrows
UPDATE conversations
SET blocked_at = NULL
WHERE id = $1
  AND blocked_at IS NOT NULL
`

func (q *Queries) SetConversationUnblocked(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, setConversationUnblocked, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumCompletedPaymentsByGuest = `-- name: SumCompletedPaymentsByGuest :one
SELECT COALESCE(SUM(p.amount_cents), 0)::bigint AS total_cents
FROM payments p
JOIN checkouts c ON c.id = p.checkout_id
WHERE c.guest_user_id = $1
  AND c.status = 'completed'
`

func (q *Queries) SumCompletedPaymentsByGuest(ctx context.Context, guestUserID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, sumCompletedPaymentsByGuest, guestUserID)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET last_activity_at = now()
WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}

const tryInsertStripeEvent = `-- name: TryInsertStripeEvent :execrows
INSERT INTO stripe_events (stripe_event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (stripe_event_id) DO NOTHING
`

type TryInsertStripeEventParams struct {
	StripeEventID string `json:"stripe_event_id"`
	EventType     string `json:"event_type"`
}

func (q *Queries) TryInsertStripeEvent(ctx context.Context, arg TryInsertStripeEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryInsertStripeEvent, arg.StripeEventID, arg.EventType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
