// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRecoveryToken = `-- name: ConsumeRecoveryToken :execrows
UPDATE chat_recovery_tokens
SET consumed_at = now()
WHERE id = $1
  AND consumed_at IS NULL
`

func (q *Queries) ConsumeRecoveryToken(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRecoveryToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRecoveryToken = `-- name: CreateRecoveryToken :one
INSERT INTO chat_recovery_tokens (conversation_id, guest_user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, guest_user_id, token_hash, expires_at, consumed_at, created_at
`

type CreateRecoveryTokenParams struct {
	ConversationID int64              `json:"conversation_id"`
	GuestUserID    int64              `json:"guest_user_id"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRecoveryToken(ctx context.Context, arg CreateRecoveryTokenParams) (*ChatRecoveryToken, error) {
	row := q.db.QueryRow(ctx, createRecoveryToken,
		arg.ConversationID,
		arg.GuestUserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ChatRecoveryToken
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.GuestUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getValidRecoveryToken = `-- name: GetValidRecoveryToken :one
SELECT id, conversation_id, guest_user_id, token_hash, expires_at, consumed_at, created_at
FROM chat_recovery_tokens
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetValidRecoveryToken(ctx context.Context, tokenHash string) (*ChatRecoveryToken, error) {
	row := q.db.QueryRow(ctx, getValidRecoveryToken, tokenHash)
	var i ChatRecoveryToken
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.GuestUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return &i, err
}
