// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSubscriptionChars = `-- name: AddSubscriptionChars :one
UPDATE subscriptions
SET chars_used = chars_used + $1,
    updated_at = now()
WHERE id = $2
  AND status IN ('active', 'trialing', 'past_due')
  AND current_period_end > now()
  AND chars_used + $1 <= $3
RETURNING id, guest_user_id, stripe_subscription_id, stripe_customer_id, status, current_period_start, current_period_end, chars_used, created_at, updated_at
`

type AddSubscriptionCharsParams struct {
	Delta     int32 `json:"delta"`
	ID        int64 `json:"id"`
	Allowance int32 `json:"allowance"`
}

func (q *Queries) AddSubscriptionChars(ctx context.Context, arg AddSubscriptionCharsParams) (*Subscription, error) {
	row := q.db.QueryRow(ctx, addSubscriptionChars, arg.Delta, arg.ID, arg.Allowance)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.GuestUserID,
		&i.StripeSubscriptionID,
		&i.StripeCustomerID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CharsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getActiveSubscriptionByGuest = `-- name: GetActiveSubscriptionByGuest :one
SELECT id, guest_user_id, stripe_subscription_id, stripe_customer_id, status, current_period_start, current_period_end, chars_used, created_at, updated_at
FROM subscriptions
WHERE guest_user_id = $1
  AND status IN ('active', 'trialing', 'past_due')
  AND current_period_end > now()
ORDER BY current_period_end DESC, id DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByGuest(ctx context.Context, guestUserID int64) (*Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByGuest, guestUserID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.GuestUserID,
		&i.StripeSubscriptionID,
		&i.StripeCustomerID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CharsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSubscriptionByStripeID = `-- name: GetSubscriptionByStripeID :one
SELECT id, guest_user_id, stripe_subscription_id, stripe_customer_id, status, current_period_start, current_period_end, chars_used, created_at, updated_at
FROM subscriptions
WHERE stripe_subscription_id = $1
`

func (q *Queries) GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID string) (*Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeID, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.GuestUserID,
		&i.StripeSubscriptionID,
		&i.StripeCustomerID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CharsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (
    guest_user_id,
    stripe_subscription_id,
    stripe_customer_id,
    status,
    current_period_start,
    current_period_end,
    chars_used
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (stripe_subscription_id) DO UPDATE
SET status = EXCLUDED.status,
    stripe_customer_id = COALESCE(EXCLUDED.stripe_customer_id, subscriptions.stripe_customer_id),
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    chars_used = CASE
        WHEN subscriptions.current_period_start IS DISTINCT FROM EXCLUDED.current_period_start THEN 0
        ELSE subscriptions.chars_used
    END,
    updated_at = now()
RETURNING id, guest_user_id, stripe_subscription_id, stripe_customer_id, status, current_period_start, current_period_end, chars_used, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	GuestUserID          int64              `json:"guest_user_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CharsUsed            int32              `json:"chars_used"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (*Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.GuestUserID,
		arg.StripeSubscriptionID,
		arg.StripeCustomerID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CharsUsed,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.GuestUserID,
		&i.StripeSubscriptionID,
		&i.StripeCustomerID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CharsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
