// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuestUser = `-- name: CreateGuestUser :one
INSERT INTO users (email, display_name)
VALUES ($1, $2)
RETURNING id, firebase_uid, email, display_name, created_at, updated_at
`

type CreateGuestUserParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateGuestUser(ctx context.Context, arg CreateGuestUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createGuestUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, email, display_name)
VALUES ($1, $2, $3)
RETURNING id, firebase_uid, email, display_name, created_at, updated_at
`

type CreateUserParams struct {
	FirebaseUid pgtype.Text `json:"firebase_uid"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.FirebaseUid, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, firebase_uid, email, display_name, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, display_name, created_at, updated_at
FROM users
WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid pgtype.Text) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, email, display_name, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserFirebase = `-- name: UpdateUserFirebase :exec
UPDATE users
SET firebase_uid = $1,
    display_name = CASE WHEN $2 = '' THEN display_name ELSE $2 END,
    updated_at = now()
WHERE id = $3
`

type UpdateUserFirebaseParams struct {
	FirebaseUid pgtype.Text `json:"firebase_uid"`
	DisplayName interface{} `json:"display_name"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateUserFirebase(ctx context.Context, arg UpdateUserFirebaseParams) error {
	_, err := q.db.Exec(ctx, updateUserFirebase, arg.FirebaseUid, arg.DisplayName, arg.ID)
	return err
}
