import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { render } from "@react-email/render";
import { createElement, type ReactElement } from "react";

import { CreatorPaidEmail } from "./creator-paid";
import { GuestReplyEmail } from "./guest-reply";
import { RecoveryEmail } from "./recovery";

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(here, "../apps/server/pkg/mailer/templates");

interface Spec {
  file: string;
  subject: string;
  text: string;
  element: ReactElement;
}

const specs: Spec[] = [
  {
    file: "recovery",
    subject: "Reopen your Penpal chat",
    text: [
      "You asked for a way back into your Penpal conversation. Open chat on this instance:",
      "{{LINK}}",
      "The link works once and expires in 24 hours. If you did not request this, you can ignore the email.",
      "Powered by Hotly",
      "https://hotly.com",
    ].join("\n\n"),
    element: createElement(RecoveryEmail),
  },
  {
    file: "creator_paid",
    subject: "New Penpal {{KIND}}",
    text: [
      "Someone just sent you a Penpal {{KIND}}. Open your inbox to read it and write back.",
      "{{INBOX}}",
      "Powered by Hotly",
      "https://hotly.com",
    ].join("\n\n"),
    element: createElement(CreatorPaidEmail),
  },
  {
    file: "guest_reply",
    subject: "You have a new Penpal reply",
    text: [
      "There is a new reply in your Penpal conversation. Open chat on this instance to read it.",
      "{{CHAT}}",
      "Powered by Hotly",
      "https://hotly.com",
    ].join("\n\n"),
    element: createElement(GuestReplyEmail),
  },
];

await mkdir(outDir, { recursive: true });

for (const spec of specs) {
  const html = await render(spec.element);
  await writeFile(path.join(outDir, `${spec.file}.html`), `<!-- Generated by bun run emails:render from emails/*.tsx. Do not edit. -->\n${html}\n`);
  await writeFile(path.join(outDir, `${spec.file}.txt`), `Subject: ${spec.subject}\n\n${spec.text}\n`);
  console.log(`wrote ${spec.file}`);
}
